### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by hramrach** [lineageos4microg/update_verifier#1]
python3 update_verifier.py lineageos4microg_pubkey.txt lineage-15.1-20181126-microG-albus.zip
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyasn1/type/namedtype.py", line 102, in getPositionByName
    return self.__nameToPosIdx[name]
KeyError: 'field-4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update_verifier.py", line 125, in <module>
    main()
  File "update_verifier.py", line 118, in main
    if not signed_file.verify(args.public_key):
  File "update_verifier.py", line 101, in verify
    signature = cert[-1][-1][-1]['field-4'].asOctets()
  File "/usr/lib/python3/dist-packages/pyasn1/type/univ.py", line 818, in __getitem__
    return self.getComponentByName(idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/univ.py", line 855, in getComponentByName
    self._componentType.getPositionByName(name)
  File "/usr/lib/python3/dist-packages/pyasn1/type/namedtype.py", line 104, in getPositionByName
    raise error.PyAsn1Error('Name %s not found' % (name,))
pyasn1.error.PyAsn1Error: Name field-4 not found

ii  python3-pyasn1 0.1.9-2      all          ASN.1 library for Python (Python 3 module)
ii  python3-rsa    3.4.2-1      all          Pure-Python RSA implementation (Python 3)

**Comment by hramrach** [comment]
Nevermind, the pyasn1 is just too old.

That said, it would not be too difficult to check that in the script itself, would it?

**Comment by corna** [comment]
The required version is stated both in README.md and in requirements.txt, it seems sufficient to me ;)

This fork just adds the LineageOS for microG key, any issue (like this one) should be forwarded to the original repository.
