### ISSUE TITLE
[Ubuntu 19.10] UnicodeEncodeError with update_verifier.py

### ISSUE THREAD

**Issue by lalejand** [lineageos4microg/update_verifier#4]
I'm on Ubuntu 19.10.
I installed python3-rsa python3-pyasn.
When I run the update verifier I get this error:
lalejand@Gedeon:~/Téléchargements$ python3 update_verifier.py lineageos4microg_pubkey lineage-16.0-20191022-microG-FP2.zip 
Traceback (most recent call last):
  File "update_verifier.py", line 125, in <module>
    main()
  File "update_verifier.py", line 118, in main
    if not signed_file.verify(args.public_key):
  File "update_verifier.py", line 103, in verify
    keydata = rsa.PublicKey.load_pkcs1(zipfile.read())
  File "/usr/lib/python3/dist-packages/rsa/key.py", line 118, in load_pkcs1
    return method(keyfile)
  File "/usr/lib/python3/dist-packages/rsa/key.py", line 292, in _load_pkcs1_pem
    der = rsa.pem.load_pem(keyfile, 'RSA PUBLIC KEY')
  File "/usr/lib/python3/dist-packages/rsa/pem.py", line 53, in load_pem
    contents = contents.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 1262: ordinal not in range(128)

**Comment by xaverdh** [comment]
Not an expert in python encoding handling, but whats your locale (what does echo $LANG say)?

**Comment by lalejand** [comment]
Thanks for trying to help. I finally installed another OS.
